# Smart Battery Charging - Essential Configuration Only

input_number:
  smart_charging_max_power:
    name: "Smart Charging Max Power"
    min: 1000
    max: 4500
    step: 100
    unit_of_measurement: "W"
    icon: mdi:lightning-bolt
    initial: 4000

input_boolean:
  smart_charging_enabled:
    name: "Smart Charging Enabled"
    icon: mdi:battery-charging-wireless
    initial: true
    
# Helper to track the active charging block
input_text:
  active_charging_block:
    name: "Active Charging Block"
    initial: "none"
    max: 20